# Generated by Django 2.1.7 on 2019-05-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default='.', max_length=100),
            preserve_default=False,
        ),
    ]
